### PR TITLE
Remove 'Ubuntu Store'

### PR DESCRIPTION
**Pull request by sverzegnassi**

### CODE REVIEW

**Comment by sverzegnassi** [comment]
*Do not merge yet*

**Comment by NeoTheThird** [comment]
I enabled branch protection.

**Comment by NeoTheThird** [comment]
It built, good job! If you think it's ready and want review, say the word.

**Comment by sverzegnassi** [comment]
@NeoTheThird We're ready! \o/

I realize that it's impossible to review this PR. I apologize, but it was inevitable.

Long story short: the app scope was actually another interface to the Ubuntu Store. There's for sure some dead code into the source code; however, we can safely say that there is no code that use a network connection.

I tested it for a while, and everything seems to work well.

In order to get the QA working faster, here's a small list of things to check:
- .click apps can be launched from the scope
- .deb apps can be launched from the scope (e.g. webbrowser-app)
- Removable .click apps can actually be removed, and scope deletes the related icon from the dash
- Install an app from OpenStore and the related icon appears on the dash
- Search for an installed app, and repeat the tests above
- Long press on an icon: app title, app icon, and related actions are properly displayed 
- Repeat the tests until the scope crashes :stuck_out_tongue: 
- In the "Manage scopes" bottom edge, "Apps" scope is listed and the icon is visible

**Review by NeoTheThird — APPROVED** [review]

**Comment by NeoTheThird** [comment]
Great work, thank you!

> I realize that it's impossible to review this PR. I apologize, but it was inevitable.

Yeah, never mind. I'm not reading 5000 lines :P

Let's get this merged, it seems to me like it should work. And if it doesn't, well, at least we'll be able to see it faster with more eyes on devel.

**Pull request merged**
